//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictonaryApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DictonaryApp.Resources.Localization.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directs to page for dictionary creation .
        /// </summary>
        internal static string AddDictionary_DestinationBtn_Hint {
            get {
                return ResourceManager.GetString("AddDictionary_DestinationBtn_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The languages do not have to be the same..
        /// </summary>
        internal static string AddDictionary_Error_LanguageEquals {
            get {
                return ResourceManager.GetString("AddDictionary_Error_LanguageEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose languages for dictionary.
        /// </summary>
        internal static string AddDictionary_Languages {
            get {
                return ResourceManager.GetString("AddDictionary_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string AddDictionary_Languages_From {
            get {
                return ResourceManager.GetString("AddDictionary_Languages_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string AddDictionary_Languages_To {
            get {
                return ResourceManager.GetString("AddDictionary_Languages_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of dictionary.
        /// </summary>
        internal static string AddDictionary_Name {
            get {
                return ResourceManager.GetString("AddDictionary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funny_dictionary.
        /// </summary>
        internal static string AddDictionary_Name_Placeholder {
            get {
                return ResourceManager.GetString("AddDictionary_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Dictionary.
        /// </summary>
        internal static string AddDictionary_Title {
            get {
                return ResourceManager.GetString("AddDictionary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddWord {
            get {
                return ResourceManager.GetString("AddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both fiels must contain words.
        /// </summary>
        internal static string AddWord_Error_EmptyText {
            get {
                return ResourceManager.GetString("AddWord_Error_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to add word.
        /// </summary>
        internal static string AddWord_Hint {
            get {
                return ResourceManager.GetString("AddWord_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word in first language.
        /// </summary>
        internal static string AddWord_Languages_From {
            get {
                return ResourceManager.GetString("AddWord_Languages_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word in second language.
        /// </summary>
        internal static string AddWord_Languages_To {
            get {
                return ResourceManager.GetString("AddWord_Languages_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a word in one language and its translation in another.
        /// </summary>
        internal static string AddWord_Name {
            get {
                return ResourceManager.GetString("AddWord_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add word.
        /// </summary>
        internal static string AddWord_Title {
            get {
                return ResourceManager.GetString("AddWord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to return to previous page.
        /// </summary>
        internal static string Back_Hint {
            get {
                return ResourceManager.GetString("Back_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you dont want save changes?.
        /// </summary>
        internal static string Back_question {
            get {
                return ResourceManager.GetString("Back_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateDictionary {
            get {
                return ResourceManager.GetString("CreateDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create dictionary.
        /// </summary>
        internal static string CreateDictionary_Hint {
            get {
                return ResourceManager.GetString("CreateDictionary_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to delete .
        /// </summary>
        internal static string Delete_Btn_Hint {
            get {
                return ResourceManager.GetString("Delete_Btn_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_dict {
            get {
                return ResourceManager.GetString("Delete_dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this dictionary?.
        /// </summary>
        internal static string Delete_Dict_question {
            get {
                return ResourceManager.GetString("Delete_Dict_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to delete this dictionary.
        /// </summary>
        internal static string Delete_Hint {
            get {
                return ResourceManager.GetString("Delete_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this word?.
        /// </summary>
        internal static string Delete_Word_question {
            get {
                return ResourceManager.GetString("Delete_Word_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditDictionary {
            get {
                return ResourceManager.GetString("EditDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit dictionary.
        /// </summary>
        internal static string EditDictionary_Title {
            get {
                return ResourceManager.GetString("EditDictionary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditWord {
            get {
                return ResourceManager.GetString("EditWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to save changes.
        /// </summary>
        internal static string EditWord_Hint {
            get {
                return ResourceManager.GetString("EditWord_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit word.
        /// </summary>
        internal static string EditWord_Title {
            get {
                return ResourceManager.GetString("EditWord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string end_btn {
            get {
                return ResourceManager.GetString("end_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning.
        /// </summary>
        internal static string Learning_Button {
            get {
                return ResourceManager.GetString("Learning_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn words.
        /// </summary>
        internal static string learning_title {
            get {
                return ResourceManager.GetString("learning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string ListOfWords {
            get {
                return ResourceManager.GetString("ListOfWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of words.
        /// </summary>
        internal static string ListOfWords_title {
            get {
                return ResourceManager.GetString("ListOfWords_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next_btn {
            get {
                return ResourceManager.GetString("next_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your finished this quiz.
        /// </summary>
        internal static string quiz_end {
            get {
                return ResourceManager.GetString("quiz_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string quiz_title {
            get {
                return ResourceManager.GetString("quiz_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score is {0}\{1}! Congrats!.
        /// </summary>
        internal static string score_result {
            get {
                return ResourceManager.GetString("score_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directs to the application settings.
        /// </summary>
        internal static string Settings_DestinationBtn_Hint {
            get {
                return ResourceManager.GetString("Settings_DestinationBtn_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
